variables:
  PROJECT_NAME: m.keyin.com
  BEARYCHAT_WEBHOOK: https://hook.bearychat.com/=bwCVf/incoming/e59850676f3f4374da2c3b0377b9b087
  DOCKER_REGISTRY: 172.26.97.56:5000
  IMAGE_NAME: "${DOCKER_REGISTRY}/${PROJECT_NAME}"
  
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - curl $BEARYCHAT_WEBHOOK -X POST -d "payload={\"text\":\"$PROJECT_NAME 开始构建\"}"
    - docker build -t "${IMAGE_NAME}:lastest" .
    - docker image tag "${IMAGE_NAME}:lastest" "${IMAGE_NAME}:$CI_COMMIT_SHA"
    - docker push "${IMAGE_NAME}:lastest"
    - docker push "${IMAGE_NAME}:$CI_COMMIT_SHA"

dev_deploy:
  stage: deploy
  before_script:
  - docker stop $PROJECT_NAME && docker rm $PROJECT_NAME || true
  script:
    - docker volume rm $PROJECT_NAME || true
    - docker run -d -p 9088:80 --name $PROJECT_NAME --mount source=$PROJECT_NAME,target=/home/app/dist "${IMAGE_NAME}:${CI_COMMIT_SHA}"
    - curl $BEARYCHAT_WEBHOOK -X POST -d "payload={\"text\":\"$PROJECT_NAME 发布成功\"}"
  dependencies:
  - build
  environment:
    name: dev
    url: http://keyin.xiaoyanzhang.com/
  only:
    refs:
      - master